---
artifacts:
  files:
    - ROOT.war
phases:
  pre_build:
    build:
      commands:
        - "echo \"Building\""
        - "mnv clean compile package"
    commands:
      -
        ? "echo \"Pre build phase - Example"
          : "downlaod dependencies...\""
    post_build:
      commands:
        - "echo \"Moving files that will be uploaded\""
        - "mv target/*.war ./ROOT.war"
version: 0.2