server:
  port: 80

build.name: @project.name@
build.version: @project.version@

spring:
  datasource:
    url: jdbc:mysql://${DB_HOSTNAME}:{$DB_PORT}/${DB_DATABASE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect